# Generated by Django 6.0.5 on 2026-06-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphupload',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='graphupload',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
