# Generated by Django 6.0.5 on 2026-06-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_rename_uploaded_at_graphupload_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GraphUpload',
            new_name='Graph',
        ),
    ]
